services:
  app-db:
    image: postgres:latest
    container_name: carevantage-app-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - carevantage-net
  
  keycloak-db:
    image: postgres:latest
    container_name: carevantage-keycloak-db
    environment:
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_KEYCLOAK}
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - carevantage-net